// AUTO-GENERATED by scripts/generate-ubuntu-data.ts — do not edit by hand.

export const strokeWidthRatio = 0.05
export const glyphWidthRatio = 0.5196470097191582
export const spaceWidthRatio = 0.21072088724584104
export const lineHeightRatio = 1.087800369685767
export const letterSpacingRatio = 0
export const capHeight = 0.6404805914972274
