import { mkdirSync, readFileSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"

const fontPath = join("dist", "TscircuitAlphabet.ttf")
const fontBuffer = readFileSync(fontPath)
const base64Font = fontBuffer.toString("base64")

const outputContent = `// Auto-generated file - do not edit manually
// Generated by scripts/encode-font.ts

export default "${base64Font}"
`

const outputPath = join("dist", "base64font.js")
mkdirSync(dirname(outputPath), { recursive: true })
writeFileSync(outputPath, outputContent)

const outputTypesPath = join("dist", "base64font.d.ts")
writeFileSync(
  outputTypesPath,
  "declare const font: string\nexport default font\n",
)

console.log(`✓ Font encoded and written to ${outputPath}`)
console.log(`  Font size: ${(base64Font.length / 1024).toFixed(2)} KB (base64)`)
console.log(`  Original size: ${(fontBuffer.length / 1024).toFixed(2)} KB`)
